"""empty message

Revision ID: 6a82c3794b3b
Revises: 4cda42aa2ba6
Create Date: 2026-01-26 18:21:56.018384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a82c3794b3b'
down_revision = '4cda42aa2ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('private_data_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('private_data_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
